-- Opt-in Hyprland window rule for OmaVM's Machine display viewer
-- (omavm-gui --display-fd, launched by `omavm open`/`Open` on a Machine).
--
-- Not loaded automatically: like OmaVM's Quickshell plugin
-- (contrib/dev.omavm.bar), this only takes effect once you explicitly
-- require it from your own Hyprland config, e.g. by adding to
-- ~/.config/hypr/windows.lua:
--
--   require("omavm-viewer")
--
-- (with this file's directory added to Hyprland's Lua package.path, or
-- copied straight into ~/.config/hypr/). See README.md for the full step.
--
-- Places the viewer on its own dedicated named workspace and fullscreens
-- it there, so a Machine's display always opens the same way instead of
-- tiling into whatever workspace you happened to be on. Deliberately a
-- plain named workspace, not a Hyprland "special" one: special
-- workspaces are scratchpad-style overlays that stay hidden until
-- explicitly toggled (hyprctl dispatch togglespecialworkspace) — a
-- window rule alone never makes them visible. A plain named workspace
-- switches the monitor to it automatically when the window opens, same
-- as any other window-rule-targeted workspace.
--
-- Conflicts with OmaVM's own "Open in an empty workspace" Settings
-- preference (also opt-in, per-environment): that preference switches to
-- a fresh empty workspace right before launching, but this window rule
-- still wins and sends the new window to the fixed "name:omavm"
-- workspace anyway. The two solve different needs (one dedicated,
-- fullscreen spot vs. a fresh workspace per environment) and aren't
-- meant to compose — use one or the other, not both.
o.window("dev.omavm.viewer", { workspace = "name:omavm", fullscreen = true })
